### PR TITLE
Move V2 samples as default samples.

### PR DESCRIPTION
**Pull request by sashi-coursera**

### CODE REVIEW

**Comment by sashi-coursera** [comment]
Oops. Some of my local changes got pushed :). I will clean it up.

**Comment by ji-su-lee** [comment]
> Oops. Some of my local changes got pushed :). I will clean it up.

Sounds good! Lmk when you're ready :)

**Comment by ji-su-lee** [comment]
lgtm!

**Review by ji-su-lee — COMMENTED** [review]
lgtm!

**Pull request closed without merging**
