### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by romeokienzler**
Improved README.md since the provided version didn't work for the local testing part

### CODE REVIEW

**Comment by saeta** [comment]
Hey @romeokienzler first of all, thanks very much for the PR, and for trying out our programming assignments system! If you have any other thoughts on what we could do to help you and other instructional teams with programming assignments, please do reach out.

Good catch. It looks like we didn't completely migrate all of the documentation & configuration to the new format that permits part id's. I'll let @ngarg-coursera chime in with his thoughts, but I think it makes more sense to either (a) have the 2 lines within the Dockerfile itself (with one commented out) [I'd like the included `Dockerfile` to work for testing without requiring further modification (for at least one of the assignments).]; or (b) update the instructions for testing the graders locally to show how to pass along command line arguments.

Currently, I'm leaning towards (b), as that most closely matches up with how things will work in our production environment.

**Comment by ngarg-coursera** [comment]
Thanks for taking the time to help improve our documentation @romeokienzler.

I agree with @saeta on doing (b) i.e. updating the instructions for testing the graders locally to show how to pass along command line arguments as it closely resembles how grading happens in the production environment.

Basically, using the following command to simulate passing in the extra cmd line params:

courseraprogramming grade local demo_grader.v1.1 $CustomGraderPath/DemoAssignmentGrader/SampleSubmission/FactoringSampleSubmission partId HxbKF

**Comment by romeokienzler** [comment]
Ok, just tested it, it works, created a new pull request on for this https://github.com/coursera/programming-assignments-demo/pull/13

**Comment by romeokienzler** [comment]
Ok, just tested it, it works, created a new pull request on for this
https://github.com/coursera/programming-assignments-demo/pull/13

Am 07/04/16 um 19:23 schrieb ngarg-coursera:
> courseraprogramming grade local demo_grader.v1.1
> $CustomGraderPath/DemoAssignmentGrader/SampleSubmission/FactoringSampleSubmission
> partId HxbKF

**Pull request closed without merging**
